name: Crypto Bot Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Check file existence
      run: |
        if [ -f "bot_signal_main.py" ]; then
          echo "File exists!"
        else
          echo "File does not exist!"
          exit 1
        fi

    - name: Run the bot
      run: |
        python bot_signal_main.py
